plugins {

}

ext {
    moduleProjects = subprojects.findAll { (it.name.startsWith('enroll')) }
    javaProjects = subprojects + rootProject
    dependencyVersions = [
            springboot   : '2.6.13',
            springcloud  : '2021.0.5',
            alicloud     : '2021.0.5.0',
            mybatis      : '2.3.1',
            easyexcel    : '4.0.3',
            pagehelper   : '1.4.7',
            druid        : '1.2.23',
            commons      : '3.13.0',
            transmittable: '2.14.4',
            auth0: '4.4.0',
            crypto: '5.7.11',
            gson: '2.10.1',
            collections4: '4.4',
    ]
}

configure(allprojects) { project ->
    buildscript {
        repositories {
            maven { url 'https://maven.aliyun.com/repository/public' }
            mavenCentral()
        }
        dependencies {
            classpath("org.springframework.boot:spring-boot-gradle-plugin:${dependencyVersions.springboot}")
        }
    }

    repositories {
        maven { url "https://maven.aliyun.com/repository/public" }
        mavenLocal()
        mavenCentral()
    }

}

configure(javaProjects) { project ->
    group = 'top.gaogle'
    version = '1.0.0-GA'

    apply plugin: 'java-library'
    apply plugin: 'idea'

    sourceCompatibility = 8
    targetCompatibility = 8

    compileJava {
        options.encoding = "UTF-8"
    }
    compileTestJava {
        options.encoding = "UTF-8"
    }

    dependencies {
        implementation platform("org.springframework.boot:spring-boot-dependencies:${dependencyVersions.springboot}")
        implementation platform("org.springframework.cloud:spring-cloud-dependencies:${dependencyVersions.springcloud}")
        implementation platform("com.alibaba.cloud:spring-cloud-alibaba-dependencies:${dependencyVersions.alicloud}")
    }
}












