rootProject.name = 'enroll-pro-microservice'
include 'enroll-pojo'
include 'enroll-auth'

include 'enroll-framework'
include 'enroll-framework:enums'
include 'enroll-framework:commons'
include 'enroll-framework:mybatis'


include 'enroll-gateway'


include 'enroll-spi'
include 'enroll-spi:auth'


include 'enroll-file'
include 'enroll-register'
include 'enroll-bill'


include 'enroll-framework:security'
include 'enroll-framework:feign'