rootProject.name = 'enroll-pro-microservice'


include 'enroll-framework'
include 'enroll-framework:enums'
include 'enroll-framework:commons'
include 'enroll-framework:mybatis'
include 'enroll-framework:security'
include 'enroll-framework:feign'
include 'enroll-framework:redis'
include 'enroll-framework:log'
include 'enroll-framework:sentinel'
include 'enroll-framework:nacos'

include 'enroll-spi'
include 'enroll-spi:auth'


include 'enroll-gateway'
include 'enroll-pojo'
include 'enroll-auth'
include 'enroll-file'
include 'enroll-register'
include 'enroll-bill'
include 'enroll-base'



include 'enroll-framework:rocketmq'