dependencies {

    implementation(project(':enroll-framework:commons')) {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-web'
    }
    implementation(project(':enroll-framework:redis')) {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-web'
    }

    implementation 'com.auth0:java-jwt:'+ project.dependencyVersions.auth0
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery'
    implementation 'org.springframework.boot:spring-boot'
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
    implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-sentinel'
    implementation 'com.alibaba.cloud:spring-cloud-alibaba-sentinel-gateway'
    implementation 'com.alibaba.csp:sentinel-datasource-nacos'
}