spring:
  application:
    name: enroll-register
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: enroll-pro
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        namespace: enroll-pro
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        file-extension: yml

server:
  port: 8082