spring:
  redis:
    host: ${REDIS_HOST:39.98.48.234}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:Redis123}
    database: ${REDIS_DB:0}
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: lb://enroll-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: register-route
          uri: lb://enroll-register
          predicates:
            - Path=/register/**
          filters:
            - StripPrefix=1


security:
  ignore:
    whites:
      - /auth/auth/login
