spring:
  redis:
    host: ${REDIS_HOST:39.98.48.234}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:Redis123}
    database: ${REDIS_DB:0}
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: lb://enroll-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: register-route
          uri: lb://enroll-register
          predicates:
            - Path=/api/register/**
          filters:
            - StripPrefix=2


security:
  captcha:
    enabled: true
    type: math
  ignore:
    whites:
      - /api/auth/auth/login
