spring:
  application:
    name: enroll-gateway
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: enroll-pro
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        namespace: enroll-pro
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        file-extension: yml
    gateway:
      routes:
        - id: auth-route
          uri: lb://enroll-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
server:
  port: 8080
