dependencies {
    implementation project(':enroll-pojo')
    implementation project(':enroll-framework:commons')
    implementation project(':enroll-framework:mybatis')
    implementation project(':enroll-framework:feign')
    implementation project(':enroll-framework:security')
    implementation project(':enroll-framework:redis')
    implementation project(':enroll-framework:log')
    implementation project(':enroll-spi:auth')

    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-seata'

    implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'


    implementation 'org.springframework.boot:spring-boot'
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-quartz'
}