dependencies {
    implementation project(':enroll-framework:commons')
    implementation project(':enroll-framework:redis')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.security:spring-security-crypto:5.7.11'
}